services:
  app:
    build: .
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "5173:80"

  db:
    image: mysql:8.0
    container_name: cargo-db
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: archeageapp
      MYSQL_USER: archeageapp
      MYSQL_PASSWORD: dev
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
